// Vite plugin that turns the build into an installable, offline-ready PWA.
//
// - App icons are drawn in code (src/art/icon.ts) and emitted as PNGs, so the
//   repo holds no icon files.
// - The web app manifest launches the game fullscreen in landscape.
// - A small service worker precaches every file in the build, so the game
//   loads offline and starts instantly on later launches.
//
// In dev the icons and manifest are served from memory; the service worker is
// only registered in production builds.

import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import type { Plugin, ResolvedConfig } from 'vite';
import { ICONS, renderIcon } from '../src/art/icon';
import { encodePNG } from './png';

const BG = '#07080d';

const SCREENSHOTS = [
  { src: 'docs/day.png', out: 'screenshots/arena.png', sizes: '844x390', label: 'The wizard in the arena' },
  { src: 'docs/day_cast.png', out: 'screenshots/cast.png', sizes: '844x390', label: 'Casting an energy ball' },
];

function manifest() {
  return {
    id: './',
    name: 'Everlands',
    short_name: 'Everlands',
    description: 'Top-down pixel-art PvE battles with friends.',
    start_url: './',
    scope: './',
    display: 'fullscreen',
    display_override: ['fullscreen', 'standalone'],
    orientation: 'landscape',
    background_color: BG,
    theme_color: BG,
    categories: ['games'],
    icons: ICONS.filter((i) => !i.name.startsWith('apple') && !i.name.startsWith('favicon')).map((i) => ({
      src: `icons/${i.name}`,
      sizes: `${i.size}x${i.size}`,
      type: 'image/png',
      purpose: i.purpose,
    })),
    screenshots: SCREENSHOTS.map((s) => ({ src: s.out, sizes: s.sizes, type: 'image/png', label: s.label })),
  };
}

const HEAD_TAGS = [
  { tag: 'link', attrs: { rel: 'manifest', href: 'manifest.webmanifest' } },
  { tag: 'link', attrs: { rel: 'icon', type: 'image/png', sizes: '32x32', href: 'icons/favicon-32.png' } },
  { tag: 'link', attrs: { rel: 'apple-touch-icon', sizes: '180x180', href: 'icons/apple-touch-icon.png' } },
];

// The service worker. Navigations go network-first so a new deploy is picked
// up on the next launch; everything else is served from the precache.
const swSource = (version: string, files: string[]) => `// Generated by scripts/pwa.ts
const CACHE = 'everlands-${version}';
const FILES = ${JSON.stringify(['./', ...files.map((f) => `./${f}`)])};

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  // Also clears caches left from before the game was renamed.
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE && /^(everlands|pixel-battle)-/.test(k)).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== location.origin) return;
  if (req.mode === 'navigate') {
    e.respondWith(
      fetch(req)
        .then((res) => {
          const copy = res.clone();
          if (res.ok) caches.open(CACHE).then((c) => c.put('./', copy));
          return res;
        })
        .catch(() => caches.match('./', { cacheName: CACHE })),
    );
    return;
  }
  e.respondWith(caches.match(req, { cacheName: CACHE }).then((hit) => hit || fetch(req)));
});
`;

export function pwa(): Plugin {
  let config: ResolvedConfig;
  const icons = new Map<string, Buffer>();
  const iconPNG = (name: string) => {
    let png = icons.get(name);
    if (!png) {
      const spec = ICONS.find((i) => i.name === name);
      if (!spec) return undefined;
      png = encodePNG(spec.size, spec.size, renderIcon(spec));
      icons.set(name, png);
    }
    return png;
  };

  return {
    name: 'everlands-pwa',
    configResolved(c) {
      config = c;
    },
    transformIndexHtml() {
      return HEAD_TAGS.map((t) => ({ ...t, injectTo: 'head' as const }));
    },
    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        const url = (req.url ?? '').split('?')[0];
        if (url.endsWith('/manifest.webmanifest')) {
          res.setHeader('Content-Type', 'application/manifest+json');
          res.end(JSON.stringify(manifest(), null, 2));
          return;
        }
        const icon = url.match(/\/icons\/([\w-]+\.png)$/);
        const png = icon && iconPNG(icon[1]);
        if (png) {
          res.setHeader('Content-Type', 'image/png');
          res.end(png);
          return;
        }
        const shot = SCREENSHOTS.find((s) => url.endsWith(`/${s.out}`));
        if (shot) {
          res.setHeader('Content-Type', 'image/png');
          res.end(readFileSync(resolve(config.root, shot.src)));
          return;
        }
        next();
      });
    },
    generateBundle() {
      for (const spec of ICONS) this.emitFile({ type: 'asset', fileName: `icons/${spec.name}`, source: iconPNG(spec.name)! });
      for (const s of SCREENSHOTS) this.emitFile({ type: 'asset', fileName: s.out, source: readFileSync(resolve(config.root, s.src)) });
      this.emitFile({ type: 'asset', fileName: 'manifest.webmanifest', source: JSON.stringify(manifest(), null, 2) });
    },
    writeBundle(_opts, bundle) {
      // Runs after every file is written, so the precache list is complete.
      const files = Object.keys(bundle).filter((f) => !f.endsWith('.map') && !f.startsWith('screenshots/')).sort();
      const hash = createHash('sha256');
      for (const f of files) {
        const item = bundle[f];
        hash.update(f);
        hash.update(item.type === 'chunk' ? item.code : item.source);
      }
      const outDir = resolve(config.root, config.build.outDir);
      writeFileSync(resolve(outDir, 'sw.js'), swSource(hash.digest('hex').slice(0, 12), files));
    },
  };
}
