// Vite plugin that turns the build into an installable, offline-ready PWA.
//
// - App icons are drawn in code (src/art/icon.ts) and emitted as PNGs, so the
//   repo holds no icon files.
// - The web app manifest launches the game standalone, with no fixed
//   orientation: on some phones (Xiaomi HyperOS) an installed app with one
//   never opens. Landscape comes from the loading screen's tap to start
//   instead (src/pwa.ts).
// - A small service worker precaches every file in the build, so the game
//   loads offline and starts instantly on later launches.
//
// - The loading screen (inline in index.html) gets the game's title logo as
//   a PNG and the pixel font's letters, so it can show both before the game
//   itself has loaded.
//
// - The same site serves a second app, Heaven Lands, from heaven/ (its own
//   page, heaven/index.html): its own manifest, icons, logo and service worker,
//   all emitted under heaven/ and installable on their own. The two service
//   workers keep apart: the root one ignores everything under heaven/ (else its
//   navigation handler would cache Heaven's page as Myths' own), each only
//   clears old caches of its own name, and Heaven's precaches the shared
//   built assets it needs from one folder up.
//
// In dev the icons, logo and manifest are served from memory; the service worker is
// only registered in production builds.

import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import type { Plugin, ResolvedConfig } from 'vite';
import { ICONS, renderIcon } from '../src/art/icon';
import { LOGO_FRAMES, mythsLogo } from '../src/art/logo';
import { GLYPHS } from '../src/art/glyphs';
import { ICONS as HEAVEN_ICONS, renderIcon as renderHeavenIcon } from '../src/heaven/art/icon';
import { LOGO_FRAMES as HEAVEN_LOGO_FRAMES, heavenLogo } from '../src/heaven/art/logo';
import { encodePNG } from './png';

const BG = '#07080d';
/** Heaven Lands' dawn: the peach its loading screen and install splash open on. */
const HEAVEN_BG = '#f6cfc4';
/** Heaven Lands' folder, in the build and on the site. */
const HEAVEN = 'heaven/';

const SCREENSHOTS = [
  { src: 'docs/day.png', out: 'screenshots/arena.png', sizes: '844x390', label: 'The wizard in the arena' },
  { src: 'docs/day_cast.png', out: 'screenshots/cast.png', sizes: '844x390', label: 'Casting an energy ball' },
];

function manifest() {
  return {
    id: './',
    name: 'Myths and Legends',
    short_name: 'Myths and Legends',
    description: 'Top-down pixel-art PvE battles with friends.',
    start_url: './',
    scope: './',
    display: 'standalone',
    background_color: BG,
    theme_color: BG,
    categories: ['games'],
    icons: ICONS.filter((i) => !i.name.startsWith('apple') && !i.name.startsWith('favicon')).map((i) => ({
      src: `icons/${i.name}`,
      sizes: `${i.size}x${i.size}`,
      type: 'image/png',
      purpose: i.purpose,
    })),
    screenshots: SCREENSHOTS.map((s) => ({ src: s.out, sizes: s.sizes, type: 'image/png', label: s.label })),
  };
}

// Heaven Lands' manifest. Its paths are relative to heaven/manifest.webmanifest,
// so they stay inside heaven/. No orientation, for the same reason as above.
function heavenManifest() {
  return {
    id: './',
    name: 'Heaven Lands',
    short_name: 'Heaven Lands',
    description: 'A cozy pixel world to build, grow and wander with friends.',
    start_url: './',
    scope: './',
    display: 'standalone',
    background_color: HEAVEN_BG,
    theme_color: HEAVEN_BG,
    categories: ['games'],
    icons: HEAVEN_ICONS.filter((i) => !i.name.startsWith('apple') && !i.name.startsWith('favicon')).map((i) => ({
      src: `icons/${i.name}`,
      sizes: `${i.size}x${i.size}`,
      type: 'image/png',
      purpose: i.purpose,
    })),
  };
}

/** The title logo's frames, stacked top to bottom, for the loading screen. */
const LOGO_FILE = 'loader/logo.png';

/** Is this file the root page's own (its icons, logo, manifest, screenshots), which Heaven doesn't need? */
const rootOnly = (f: string) =>
  f === 'index.html' || f === 'manifest.webmanifest' || f === 'sw.js' || /^(icons|loader|screenshots)\//.test(f);

const HEAD_TAGS = [
  { tag: 'link', attrs: { rel: 'preload', as: 'image', href: LOGO_FILE } },
  { tag: 'link', attrs: { rel: 'manifest', href: 'manifest.webmanifest' } },
  { tag: 'link', attrs: { rel: 'icon', type: 'image/png', sizes: '32x32', href: 'icons/favicon-32.png' } },
  { tag: 'link', attrs: { rel: 'apple-touch-icon', sizes: '180x180', href: 'icons/apple-touch-icon.png' } },
];

// The service worker. Navigations go network-first so a new deploy is picked
// up on the next launch; everything else is served from the precache.
const swSource = (version: string, files: string[]) => `// Generated by scripts/pwa.ts
const CACHE = 'myths-${version}';
const FILES = ${JSON.stringify(['./', ...files.map((f) => `./${f}`)])};
// Heaven Lands lives in its own folder with its own service worker: leave it alone.
const HEAVEN = new URL('${HEAVEN}', self.registration.scope).href;

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  // Also clears caches left from before the game was renamed.
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE && /^(myths|everlands|pixel-battle)-/.test(k)).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== location.origin) return;
  if (req.url.startsWith(HEAVEN)) return;
  if (req.mode === 'navigate') {
    e.respondWith(
      fetch(req)
        .then((res) => {
          const copy = res.clone();
          if (res.ok) caches.open(CACHE).then((c) => c.put('./', copy));
          return res;
        })
        .catch(() => caches.match('./', { cacheName: CACHE })),
    );
    return;
  }
  e.respondWith(caches.match(req, { cacheName: CACHE }).then((hit) => hit || fetch(req)));
});
`;

// Heaven Lands' service worker, at heaven/sw.js: the same strategy under its own
// cache name. Its files are relative to heaven/, so the shared built assets are
// one folder up ('../assets/...'), and its own page is its './'.
const heavenSwSource = (version: string, files: string[]) => `// Generated by scripts/pwa.ts
const CACHE = 'heaven-${version}';
const FILES = ${JSON.stringify(['./', ...files])};

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  // Only Heaven's own old caches: Myths' are its own service worker's business.
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE && /^heaven-/.test(k)).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== location.origin) return;
  if (req.mode === 'navigate') {
    e.respondWith(
      fetch(req)
        .then((res) => {
          const copy = res.clone();
          if (res.ok) caches.open(CACHE).then((c) => c.put('./', copy));
          return res;
        })
        .catch(() => caches.match('./', { cacheName: CACHE })),
    );
    return;
  }
  e.respondWith(caches.match(req, { cacheName: CACHE }).then((hit) => hit || fetch(req)));
});
`;

/** A short hash of a list of built files and their contents, naming a cache. */
function versionOf(files: string[], bundle: Record<string, { type: string; code?: string; source?: string | Uint8Array }>): string {
  const hash = createHash('sha256');
  for (const f of files) {
    const item = bundle[f];
    hash.update(f);
    hash.update(item.type === 'chunk' ? item.code! : item.source!);
  }
  return hash.digest('hex').slice(0, 12);
}

export function pwa(): Plugin {
  let config: ResolvedConfig;
  const icons = new Map<string, Buffer>();
  let logo: { png: Buffer; w: number; h: number } | null = null;
  const logoPNG = () => {
    if (!logo) {
      const l = mythsLogo();
      logo = { png: encodePNG(l.sheet.w, l.sheet.h, l.sheet.data), w: l.frameW, h: l.frameH };
    }
    return logo;
  };
  const iconPNG = (name: string) => {
    let png = icons.get(name);
    if (!png) {
      const spec = ICONS.find((i) => i.name === name);
      if (!spec) return undefined;
      png = encodePNG(spec.size, spec.size, renderIcon(spec));
      icons.set(name, png);
    }
    return png;
  };
  // Heaven Lands' logo and icons, drawn once on first use like the root's.
  let heavenLogoPng: { png: Buffer; w: number; h: number } | null = null;
  const heavenLogoPNG = () => {
    if (!heavenLogoPng) {
      const l = heavenLogo();
      heavenLogoPng = { png: encodePNG(l.sheet.w, l.sheet.h, l.sheet.data), w: l.frameW, h: l.frameH };
    }
    return heavenLogoPng;
  };
  const heavenIcons = new Map<string, Buffer>();
  const heavenIconPNG = (name: string) => {
    let png = heavenIcons.get(name);
    if (!png) {
      const spec = HEAVEN_ICONS.find((i) => i.name === name);
      if (!spec) return undefined;
      png = encodePNG(spec.size, spec.size, renderHeavenIcon(spec));
      heavenIcons.set(name, png);
    }
    return png;
  };

  return {
    name: 'myths-pwa',
    configResolved(c) {
      config = c;
    },
    transformIndexHtml(_html, ctx) {
      // What the loading screen needs before the game has loaded: the logo's size and the font's letters.
      // Heaven's page gets its own logo; the head tags are relative, so on its
      // page they already point at heaven/'s manifest, icons and logo.
      const heaven = /(^|\/)heaven\/index\.html$/.test((ctx.filename ?? '').replace(/\\/g, '/')) || ctx.path.endsWith(`/${HEAVEN}index.html`);
      const { w, h } = heaven ? heavenLogoPNG() : logoPNG();
      const frames = heaven ? HEAVEN_LOGO_FRAMES : LOGO_FRAMES;
      const boot = `window.__BOOT=${JSON.stringify({ logo: { src: LOGO_FILE, w, h, frames }, glyphs: GLYPHS })};`;
      return [{ tag: 'script', children: boot, injectTo: 'head-prepend' as const }, ...HEAD_TAGS.map((t) => ({ ...t, injectTo: 'head' as const }))];
    },
    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        const url = (req.url ?? '').split('?')[0];
        // Heaven Lands' own files first, as the root's patterns below would match them too.
        if (url.startsWith(`/${HEAVEN}`)) {
          if (url.endsWith('/manifest.webmanifest')) {
            res.setHeader('Content-Type', 'application/manifest+json');
            res.end(JSON.stringify(heavenManifest(), null, 2));
            return;
          }
          if (url.endsWith(`/${LOGO_FILE}`)) {
            res.setHeader('Content-Type', 'image/png');
            res.end(heavenLogoPNG().png);
            return;
          }
          const icon = url.match(/\/icons\/([\w-]+\.png)$/);
          const png = icon && heavenIconPNG(icon[1]);
          if (png) {
            res.setHeader('Content-Type', 'image/png');
            res.end(png);
            return;
          }
          next();
          return;
        }
        if (url.endsWith('/manifest.webmanifest')) {
          res.setHeader('Content-Type', 'application/manifest+json');
          res.end(JSON.stringify(manifest(), null, 2));
          return;
        }
        if (url.endsWith(`/${LOGO_FILE}`)) {
          res.setHeader('Content-Type', 'image/png');
          res.end(logoPNG().png);
          return;
        }
        const icon = url.match(/\/icons\/([\w-]+\.png)$/);
        const png = icon && iconPNG(icon[1]);
        if (png) {
          res.setHeader('Content-Type', 'image/png');
          res.end(png);
          return;
        }
        const shot = SCREENSHOTS.find((s) => url.endsWith(`/${s.out}`));
        if (shot) {
          res.setHeader('Content-Type', 'image/png');
          res.end(readFileSync(resolve(config.root, shot.src)));
          return;
        }
        next();
      });
    },
    generateBundle() {
      for (const spec of ICONS) this.emitFile({ type: 'asset', fileName: `icons/${spec.name}`, source: iconPNG(spec.name)! });
      this.emitFile({ type: 'asset', fileName: LOGO_FILE, source: logoPNG().png });
      for (const s of SCREENSHOTS) this.emitFile({ type: 'asset', fileName: s.out, source: readFileSync(resolve(config.root, s.src)) });
      this.emitFile({ type: 'asset', fileName: 'manifest.webmanifest', source: JSON.stringify(manifest(), null, 2) });
      for (const spec of HEAVEN_ICONS) this.emitFile({ type: 'asset', fileName: `${HEAVEN}icons/${spec.name}`, source: heavenIconPNG(spec.name)! });
      this.emitFile({ type: 'asset', fileName: `${HEAVEN}${LOGO_FILE}`, source: heavenLogoPNG().png });
      this.emitFile({ type: 'asset', fileName: `${HEAVEN}manifest.webmanifest`, source: JSON.stringify(heavenManifest(), null, 2) });
    },
    writeBundle(_opts, bundle) {
      // Runs after every file is written, so the precache list is complete.
      const all = Object.keys(bundle).filter((f) => !f.endsWith('.map') && !f.startsWith('screenshots/')).sort();
      const outDir = resolve(config.root, config.build.outDir);
      // Myths: everything but Heaven's folder.
      const files = all.filter((f) => !f.startsWith(HEAVEN));
      writeFileSync(resolve(outDir, 'sw.js'), swSource(versionOf(files, bundle), files));
      // Heaven: its own folder (its page is its './') and the shared assets, not the root page's own files.
      const heavenFiles = all.filter((f) => f !== `${HEAVEN}index.html` && !rootOnly(f));
      if (bundle[`${HEAVEN}index.html`]) {
        const rel = heavenFiles.map((f) => (f.startsWith(HEAVEN) ? `./${f.slice(HEAVEN.length)}` : `../${f}`));
        writeFileSync(resolve(outDir, `${HEAVEN}sw.js`), heavenSwSource(versionOf([`${HEAVEN}index.html`, ...heavenFiles], bundle), rel));
      }
    },
  };
}
